platform: linux
image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
inputs:
- name: nexus-boshrelease
outputs:
- name: nexus-boshrelease-tarball
run:
  path: bash
  args:
  - -c
  - | 
    bosh create-release \
      --tarball=nexus-boshrelease-tarball/dev-release.tgz \
      --dir=nexus-boshrelease \
      --timestamp-version
