platform: linux
image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
inputs:
- name: nexus-boshrelease
- name: version
outputs:
- name: final-nexus-boshrelease-tarball
run:
  path: bash
  args:
  - -c
  - | 
    version=$(<version/version)
    bosh create-release \
      --tarball=final-nexus-boshrelease-tarball/nexus-boshrelease-v$version.tgz \
      --dir=nexus-boshrelease \
      --final \
      --version="$version"
